services:
  - type: web
    name: mingo-app
    runtime: docker
    repo: https://github.com/charanjalluri/mingo
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite+aiosqlite:///./mingo.db

